Feature/add rest endpoints for product service
MSurmach/webshop pull request #6
Opened 2023-08-02 06:34 UTC by MSurmach

2023-08-02 06:48 UTC, Tyomich4736 requested changes

2023-08-02 06:48 UTC, Tyomich4736 commented on product-service/src/main/java/com/intexsoft/webshop/productservice/controller/SubcategoryController.java
> +@RequestMapping("/category/{categoryId}/subcategory")
categoryId тут не нужно, т.к. оно используется не во всех методах

2023-08-02 06:48 UTC, Tyomich4736 commented on product-service/src/main/java/com/intexsoft/webshop/productservice/controller/SubcategoryController.java
> +                                                            @PathVariable @Positive Long categoryId) {
Лучше сделать categoryId частью SubcategoryCreateDto

2023-08-02 06:48 UTC, Tyomich4736 commented on product-service/src/main/java/com/intexsoft/webshop/productservice/mapper/AttributeValueMapper.java
> +        Attribute attribute = new Attribute();
То есть на каждое новое AttributeValue в базе будет создаваться новый Attribute?

2023-08-04 05:19 UTC, MSurmach commented on product-service/src/main/java/com/intexsoft/webshop/productservice/controller/SubcategoryController.java
> +@RequestMapping("/category/{categoryId}/subcategory")
Разбиты на отдельные контроллеры /category / subcategory

2023-08-04 05:19 UTC, MSurmach commented on product-service/src/main/java/com/intexsoft/webshop/productservice/controller/SubcategoryController.java
> +                                                            @PathVariable @Positive Long categoryId) {
сделано

2023-08-04 05:20 UTC, MSurmach commented on product-service/src/main/java/com/intexsoft/webshop/productservice/mapper/AttributeValueMapper.java
> +        Attribute attribute = new Attribute();
Логика создания и обновления продукта отрефакторена

2023-08-04 06:48 UTC, Tyomich4736 requested changes

2023-08-04 06:48 UTC, Tyomich4736 commented on product-service/src/main/java/com/intexsoft/webshop/productservice/service/impl/ProductServiceImpl.java
> +        if (isNull(attributeValueCreateDtos)) return null;
Хорошим тоном считается вызывать статические методы через имя их класса, а не с import static

2023-08-04 06:48 UTC, Tyomich4736 commented on product-service/src/main/java/com/intexsoft/webshop/productservice/service/impl/ProductServiceImpl.java
> +            Image image = product_idImage_map.get(imageId);
Используй строго camelCase для именования переменных

2023-08-04 06:48 UTC, Tyomich4736 commented on product-service/src/main/java/com/intexsoft/webshop/productservice/exception/notfound404/AttributeNotFoundException.java
> +        super(ATTRIBUTE, attributeId);
В идеале тоже использовать элемент enum через его имя

2023-08-04 06:48 UTC, Tyomich4736 commented on product-service/src/main/java/com/intexsoft/webshop/productservice/service/impl/ProductServiceImpl.java
> +                    attribute.setLabel(attributeIdLabelMap.get(attributeValueCreateDto.getAttributeId()));
Лишняя работа. В идеале лучше создавать новую сущность через new когда мы действительно хотим создать новую сущность в базе. Тогда не будет визуальной путаницы. Здесь выше можно создать мапу атрибутов по id (Map<Long, Attribute>) и при создании AttributeValu просто засетать атрибут из мапы

2023-08-04 06:58 UTC, MSurmach commented on product-service/src/main/java/com/intexsoft/webshop/productservice/service/impl/ProductServiceImpl.java
> +        if (isNull(attributeValueCreateDtos)) return null;
убрал статические импорты из этого класса

2023-08-04 06:59 UTC, MSurmach commented on product-service/src/main/java/com/intexsoft/webshop/productservice/service/impl/ProductServiceImpl.java
> +            Image image = product_idImage_map.get(imageId);
Переименовано в camelCase

2023-08-04 07:05 UTC, MSurmach commented on product-service/src/main/java/com/intexsoft/webshop/productservice/exception/notfound404/AttributeNotFoundException.java
> +        super(ATTRIBUTE, attributeId);
Поправил импорты. Вызов enum через класс

2023-08-04 07:29 UTC, Tyomich4736 approved these changes

2023-08-04 07:29 UTC, merged