create order orchestrator with camunda
MSurmach/webshop pull request #7
Opened 2023-08-17 11:42 UTC by MSurmach

2023-08-18 06:49 UTC, Tyomich4736 requested changes

2023-08-18 06:49 UTC, Tyomich4736 commented on order-service/src/main/java/com/intexsoft/webshop/orderservice/dto/order/OrderCreateDto.java
> +    String paymentMethod;
Мы можем просто принимать параметр с типом PaymentMethod

2023-08-18 06:49 UTC, Tyomich4736 commented on user-service/src/main/java/com/intexsoft/webshop/userservice/mapper/UserEventMapper.java
> +    UserCheckedEvent toUserCheckedEvent(boolean checkResult, CheckOrderUserCommand checkOrderUserCommand);
Не очевидно куда присваивается checkResult. Обычно в мапперах для всех полей указывается @Mapping, даже когда поля нужно игнорировать. Это относится и ко всем остальным мапперам

2023-08-18 06:49 UTC, Tyomich4736 commented on order-orchestrator/src/main/java/com/intexsoft/webshop/orderorchestrator/producer/AbstractOrderOrchestratorCommandProducer.java
> +public abstract class AbstractOrderOrchestratorCommandProducer implements OrderOrchestratorCommandProducer {
Вряд ли у нас подразумевается наличие какого-то особенного функционала для какого-то продюсера. Проще просто сделать один сервис с четырьмя методами для отправки сообщения

2023-08-18 06:49 UTC, Tyomich4736 commented on order-orchestrator/src/main/java/com/intexsoft/webshop/orderorchestrator/producer/AbstractOrderOrchestratorCommandProducer.java
> +    public void convertAndSendCommand(BaseCommand baseCommand, CommandType commandType) {
Что будет, если я вызову этот метод с baseCommand, не соответствующей commandType? Лучше сделать у baseCommand абстрактный метод (getCommandType() например), который будет переопределятся у каждой реализации и возвращать соответствующий этой реализации тип

2023-08-18 06:49 UTC, Tyomich4736 commented on order-orchestrator/src/main/java/com/intexsoft/webshop/orderorchestrator/service/impl/OrderOrchestratorUserTaskProcessorImpl.java
> +        while (Objects.isNull(task = taskQuery.singleResult())) {
Есть риск войти в бесконечный цикл, нужно придумать другое решение и предусмотреть такую ситуацию

2023-08-18 07:16 UTC, MSurmach commented on order-service/src/main/java/com/intexsoft/webshop/orderservice/dto/order/OrderCreateDto.java
> +    String paymentMethod;
Да можем. Тут я вкладывал смысл в валидацию самого переданного значения, чтобы соответствовало enum. Либо можно убрать валидацию мою кастомную и перехватывать exception в случае неправильной строки в теле запроса. Exception  такой :`HttpMessageNotReadableException: JSON parse error: Cannot deserialize value of type `com.intexsoft.webshop.orderservice.model.enums.PaymentMethod` from String "CARD78": not one of the values accepted for Enum class: [CARD, CASH]]`

2023-08-18 07:56 UTC, MSurmach commented on order-orchestrator/src/main/java/com/intexsoft/webshop/orderorchestrator/producer/AbstractOrderOrchestratorCommandProducer.java
> +public abstract class AbstractOrderOrchestratorCommandProducer implements OrderOrchestratorCommandProducer {
Заменил на одного продюсера `OrderOrchestratorCommandProducerImpl` в котором четыре метода для каждой команды. Exchanges and routings в этом же сервисе для рассылки в каждый сервис

2023-08-18 08:01 UTC, MSurmach commented on order-orchestrator/src/main/java/com/intexsoft/webshop/orderorchestrator/producer/AbstractOrderOrchestratorCommandProducer.java
> +    public void convertAndSendCommand(BaseCommand baseCommand, CommandType commandType) {
Сообщение отошлется, просто роутинг будет не совсем корректный со стороны продюсера, но для лисенара в сервисах роли не сыграет, так как там прописан роутинг для комманд через  # на конце. Тут я это сделал для передачи в routing в качестве ключа на конце. Убрал это, в продюсере теперь методы для каждого ивента (не через родительский класс). Routing-key который конкатенируется к основному routing прописал в application.yaml как делал раньше.

2023-08-18 09:01 UTC, MSurmach commented on user-service/src/main/java/com/intexsoft/webshop/userservice/mapper/UserEventMapper.java
> +    UserCheckedEvent toUserCheckedEvent(boolean checkResult, CheckOrderUserCommand checkOrderUserCommand);
Поправил все мапперы, указал явный @Mapping для всех target полей

2023-08-18 12:01 UTC, MSurmach commented on order-orchestrator/src/main/java/com/intexsoft/webshop/orderorchestrator/service/impl/OrderOrchestratorUserTaskProcessorImpl.java
> +        while (Objects.isNull(task = taskQuery.singleResult())) {
сделал через свой ретрай в`OrderOrchestratorUserTaskProcessorImpl.class`. 12 попыток, 3 сек задержка между ними.

2023-08-23 06:23 UTC, Tyomich4736 commented on order-service/src/main/java/com/intexsoft/webshop/orderservice/dto/order/OrderCreateDto.java
> +    String paymentMethod;
Да, давай лучше перехватим такой Exception и преобразуем его в красивый респонс

2023-08-23 07:20 UTC, MSurmach commented on order-service/src/main/java/com/intexsoft/webshop/orderservice/dto/order/OrderCreateDto.java
> +    String paymentMethod;
Удалил кастомную валидацию, принимаю сразу PaymentMethod  в dto. Добавил handler на JsonMappingException (более узкий чем HttpMessageNotReadableException и инфы об исключении поменьше неинтереной для пользователя).

2023-08-23 07:29 UTC, Tyomich4736 approved these changes

2023-08-23 07:29 UTC, merged